apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: labelpod
  name: labelpod
spec:
  containers:
  - image: perl
    name: labelpod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
