apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-world1
  name: hello-world1
spec:
  containers:
  - image: hello-world
    name: hello-world1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeSelector:
    env: test 
status: {}

