apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-world2
  name: hello-world2
spec:
  nodeName: kind-worker      
  containers:
  - image: hello-world
    name: hello-world2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeSelector:
    env: test 
status: {}

