apiVersion: batch/v1
kind: Job
metadata:
  name: countdown1
spec:
  parallelism:    5
  template:
    metadata:
      name: countdown1
    spec:
      containers:
      - name: counter1
        image: centos:6
        command:
         - sleep
         - "10"
      restartPolicy: Never
