apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mynginx4
  name: mynginx4
spec:
  containers:
  - image: nginx
    name: mynginx4
    resources: {}
    env:
      - name: PASSWORD      
        valueFrom:
          secretKeyRef:
            name: hari-secret
            key: password 

  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
