apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mynginx2
  name: mynginx2
spec:
  containers:
  - image: nginx
    name: mynginx2
    resources: {}
    env:
      - name: ABC      
        valueFrom:
          configMapKeyRef:
            name: hari-cm1
            key: VAR1

  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
